### ISSUE TITLE
Проблемы в YooTheme PRO

### ISSUE THREAD

**Issue by kernusr** [AlekVolsk/ytvideo#2]
При открытии редактора yoothemepro в админке, в шапке вылазит модалка от плагина
![Аннотация 2019-10-08 133749](https://user-images.githubusercontent.com/16020878/66389347-da830600-e9d0-11e9-9d32-3109eb96bd74.jpg)

@septdir делает проверку на редактор прошки вот так:
`$customizer = (!empty($this->app->input->get('customizer')));`

**Comment by AlekVolsk** [comment]
потому что модалка от кнопки не предусматривает админку прошки, она предусматривает админку джумлы, которая работает на bs2, под каждый билдер подделываться никто не будет

**Comment by kernusr** [comment]
Предлагаю добавить `style="display: none;"` к модалке, по-умолчанию. Это позволит избавит от проблем, в компонентах, в которых переопределены стандартные стили и нет bs2. Это касается не только прошки!

**Comment by AlekVolsk** [comment]
я подумаю над возможностью внедрить шаблон для плагина кнопки (обычно плаги редакторных кнопок не имеют шаблонов вообще), не быстро

**Comment by AlekVolsk** [comment]
Можно переопределить в шаблон плагина кнопки в вашем основном шаблоне в папке `/templates/{$template_name}/html/plg_editors-xtd_vmvideobtn/default.php`.
