### ISSUE TITLE
RegExp много шорткода на 1 строке не работает

### ISSUE THREAD

**Issue by CB9TOIIIA** [AlekVolsk/ytvideo#3]
Код:
![image](https://user-images.githubusercontent.com/1074710/81588000-84d86700-93c0-11ea-9993-97e71705abff.png)
```
{ytvideo https://www.youtube.com/watch?v=E-yoRf6M9o0|16:9}{ytvideo https://www.youtube.com/watch?v=anI781DJeAk|16:9}{ytvideo https://www.youtube.com/watch?v=y9yk-BzXtuQ|16:9}
```
Результат:

![image](https://user-images.githubusercontent.com/1074710/81587965-78eca500-93c0-11ea-8a14-3d440b9e3cc3.png)

Требуется делать шорткод только с новой строки

```
{ytvideo https://www.youtube.com/watch?v=E-yoRf6M9o0|16:9}
{ytvideo https://www.youtube.com/watch?v=anI781DJeAk|16:9}
{ytvideo https://www.youtube.com/watch?v=y9yk-BzXtuQ|16:9}
```

**Comment by AlekVolsk** [comment]
Если шорткоды в одной строке в теле материала обёрнуты в любой тег, то такого эффекта нет, в противном случае на выходе J сама оборачивает строку в тег абзаца и преобразовывает ссылки в разметку, в итоге изначальная строка

```
{ytvideo https://www.youtube.com/watch?v=E-yoRf6M9o0|16:9}{ytvideo https://www.youtube.com/watch?v=anI781DJeAk|16:9}{ytvideo https://www.youtube.com/watch?v=y9yk-BzXtuQ|16:9}
```

превращается в

```
<p>{ytvideo <a href="https://www.youtube.com/watch?v=E-yoRf6M9o0|16:9}{ytvideo">https://www.youtube.com/watch?v=E-yoRf6M9o0|16:9}{ytvideo</a> <a href="https://www.youtube.com/watch?v=anI781DJeAk|16:9">https://www.youtube.com/watch?v=anI781DJeAk|16:9</a>}{ytvideo <a href="https://www.youtube.com/watch?v=y9yk-BzXtuQ|16:9">https://www.youtube.com/watch?v=y9yk-BzXtuQ|16:9</a>}</p>
```
после чего плагин работает уже с разметкой внутри шорткода

Рекомендуется оборачивать строку из нескольких шорткодов в любой блочный тег, лучше всего в <div>. По идее, редактор должен оборачивать строку автоматически в тег абзаца, если редактор не делает этого автоматически - проблема редактора, ответственность редактирующего материал
