### ISSUE TITLE
Не инициализируется видео по шорткоду в материалах

### ISSUE THREAD

**Issue by damarkuzz** [AlekVolsk/ytvideo#6]
Здравствуйте! Не инициализируется видео по шорткоду в материалах (в тексте материала). Использую без редактора. При этом в текущем материале всё успешно работает через кастомные поля.

**Comment by AlekVolsk** [comment]
Непонятно, что подразумевается под кастомными полями и какова их связь с шорткодами. Приведите пример страницы, на которой не работает.
